version: 0.2

env:
  variables:
    app_version: "2.0"
            
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
  pre_build:
    commands:
      - echo Installing NPM dependencies...
      - npm i
      - mocha
artifacts:
  files:
    - '**/*'